version: '3'

services:
      postgres:
            container_name: cssapp_postgres
            image: postgres:latest
            restart: always
            env_file: .env
            environment:
                  - POSTGRES_USER=localhost
                  - POSTGRES_PASSWORD=ADMIN
                  - POSTGRES_DB=postgresql
            volumes:
                  - postgres:/var/lib/postgres/data
            ports:
                  - 5000

volumes:
      postgres:
