version: '3'

services:
    postgres:
        container_name: cssapp_postgres
        image: postgres:latest
        restart: always
        environment:
            - POSTGRES_USER=cssapp
            - POSTGRES_PASSWORD=cssapp
            - POSTGRES_DB=cssapp
        volumes:
            - postgres:/var/lib/postgres/data
        expose:
            - 5432
    redis:
        container_name: cssapp_redis
        image: redis:latest
        restart: always
        volumes:
            - redis:/var/lib/redis/data
        expose:
            - 6379

    api:
        container_name: cssapp_api
        restart: unless-stopped
        links:
            - redis
            - postgres
        env_file: .env.prod
        build:
            context: ./
            dockerfile: Dockerfile
        ports:
            - 80:4000

volumes:
    postgres:
    redis:
