version: '3'

services:
    postgres:
        container_name: cssapp_postgres
        image: postgres:latest
        restart: always
        environment:
            - POSTGRES_USER=cssapp
            - POSTGRES_PASSWORD=cssapp
            - POSTGRES_DB=cssapp
        volumes:
            - postgres:/var/lib/postgres/data
        ports:
            - 5432:5432

    redis:
        container_name: cssapp_redis
        image: redis:latest
        restart: always
        volumes:
            - redis:/var/lib/redis/data
        ports:
            - 6379:6379

volumes:
    postgres:
    redis: